# Generated by Django 2.1.8 on 2019-06-10 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
